version: "3"

services:
  whisper:
    image: rhasspy/wyoming-whisper
    container_name: whisper
    ports:
      - 10300:10300
    restart: unless-stopped 
    command: --model tiny-int8 --language fr
    
  piper:
    image: rhasspy/wyoming-piper
    container_name: piper
    ports:
      - 10200:10200
    restart: unless-stopped 
    command: --voice fr-gilles-low